server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Secutity_System?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: komputerek
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop


    properties:
      mail:
        smtp:
          starttls:
            enable: true

